name: man_of_heal
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.6+6

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  circular_countdown_timer: ^0.2.2
  cloud_firestore: ^4.3.2
  countdown_progress_indicator: ^0.1.2
  crypto: ^3.0.2
  cupertino_icons: ^1.0.5
  firebase_auth: ^4.2.6
  firebase_core: ^2.5.0
  firebase_messaging: ^14.2.2
  flutter:
    sdk: flutter
  flutter_calendar_carousel: ^2.4.0
  flutter_countdown_timer: ^4.1.0
  flutter_launcher_icons: ^0.13.0
  flutter_local_notifications: ^15.1.0+1
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.5.4
  flutter_stripe: ^9.0.0+1
  flutter_svg: ^2.0.0+1
  get: ^4.6.5
  google_fonts: ^5.0.0
  google_sign_in: ^6.0.2
  http: ^1.0.0
  lottie: ^2.2.0
  package_info_plus: ^4.0.2
  shared_preferences: ^2.0.15
  sign_in_with_apple: ^5.0.0
  timeago: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo_new.png"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/icons/
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #`
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
