name: man_of_heal
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.6+6

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Add the dependency for the Firebase Core Flutter SDK
  firebase_core: ^2.5.0
  cloud_firestore: ^4.3.2
  firebase_auth: ^4.2.6
  firebase_messaging: ^14.2.2

  flutter_local_notifications: ^13.0.0


  #time-ago lib
  timeago: ^3.3.0

  # animation loader...
  lottie: ^2.2.0

  #get-x state, route management and dependency injection
  get: ^4.6.5

  #count_down_timer_progress_bar
  countdown_progress_indicator: ^0.1.2

  #Google Sign in
  google_sign_in: ^6.0.2

  #Flutter count down timer, used in Questions or answer details
  flutter_countdown_timer: ^4.1.0

 # used in quiz
  circular_countdown_timer: ^0.2.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

  #table_calendar: ^3.0.3
  flutter_calendar_carousel: ^2.4.0
  #stripe with dio for http requests

  flutter_stripe: ^9.0.0+1
  #flutter_stripe_web: ^1.0.0

  http: ^0.13.5

  #rating bar
  flutter_rating_bar: ^4.0.1

  #flutter load svg
  flutter_svg: ^2.0.0+1
  google_fonts: ^4.0.3
  flutter_screenutil: ^5.5.4

  #shared_preferences
  shared_preferences: ^2.0.15

  package_info_plus: ^3.0.3
  flutter_launcher_icons: ^0.12.0


  #restart app
  #flutter_phoenix: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
      sdk: flutter

flutter_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/logo/logo_new.png"
    remove_alpha_ios: true
    min_sdk_android: 21 # android min sdk min:16, default 21




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/icons/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #`
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
